### ISSUE TITLE
Dataset split issue

### ISSUE THREAD

**Issue by anosorae** [NjtechCVLab/RSTPReid-Dataset#2]
In your description, "For data division, 3701 (index < 18505), 200 (18505 <= index < 19505) and 200 (index >= 19505) identities are utilized for training, validation and testing, respectively (Marked by item 'split' in the json file)."
BUT I found in the json file, the train, test, val split are not the same as you said.

Following are what I got:
| subset | ids  | images | captions |
| :-----| ----: | :----: | :---:|
| train  | 3901 | 19505  |  39010   |
|  test  | 100  |  500   |   1000   |
|  val   | 100  |  500   |   1000   |

So which spilt is correct?

**Comment by ZJWang9928** [comment]
Thanks for your interest in our work. The split with 3701 (index < 18505), 200 (18505 <= index < 19505) and 200 (index >= 19505) identities for training, validation and test sets, respectively, is the correct one. Please try to re-download the newest version of our RSTPReid dataset, which we have checked again.

**Comment by anosorae** [comment]
Thank you for your quick reply. I re-download the dataset and the issue is solved.
